<?php

namespace MetaSyntactical\Mime\Tests;

use MetaSyntactical\Mime\Magic;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-22 at 19:55:46.
 */
class MagicTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Magic
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Magic;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        Magic::setDefaultMagicFile();
    }

    public function testExpectedExceptionIsThrownIfProvidedMagicFileDoesNotExist()
    {
        $this->setExpectedException(
            'MetaSyntactical\\Mime\\Exception\\FileNotFoundException',
            'File does not exist or is not readable:'
        );
        new Magic('/notExistingDummyPath/magic');
    }

    /**
     * @covers MetaSyntactical\Mime\Magic::setDefaultMagicFile
     */
    public function testSettingNonExistingDefaultMagicFileThrowsException()
    {
        $this->setExpectedException(
            'MetaSyntactical\\Mime\\Exception\\FileNotFoundException',
            '/notExistingDummyPath/magic'
        );
        Magic::setDefaultMagicFile('/notExistingDummyPath/magic');
    }

    /**
     * @covers MetaSyntactical\Mime\Magic::setDefaultMagicFile
     */
    public function testDefaultMagicFileIsUsedOnInitialization()
    {
        Magic::setDefaultMagicFile(__DIR__.'/_Data/magic');
        $magic = new Magic();
        self::assertNull($magic->getMimeType(__DIR__.'/_Data/magic'));
    }

    /**
     * @covers MetaSyntactical\Mime\Magic::getMimeType
     */
    public function testRetrievingMimeTypeReturnsExpectedResults()
    {
        self::assertEquals(
            'image/jpeg',
            $this->object->getMimeType(__DIR__.'/_Data/Fireworks_Australia_Day_11_-_2_(Public_Domain).jpg')
        );

        $smallMagic = new Magic(__DIR__.'/_Data/magic');
        self::assertNull($smallMagic->getMimeType(__DIR__.'/_Data/magic'));
        self::assertNull($this->object->getMimeType(__DIR__.'/_Data/magic'));
    }

    /**
     * @covers MetaSyntactical\Mime\Magic::isMimeType
     */
    public function testCheckingFilesHaveExpectedMimeTypes()
    {
        self::assertTrue(
            $this->object->isMimeType(__DIR__.'/_Data/Fireworks_Australia_Day_11_-_2_(Public_Domain).jpg', 'image/jpeg')
        );
        $fileArray = array(__DIR__.'/_Data/Fireworks_Australia_Day_11_-_2_(Public_Domain).jpg');
        self::assertEquals(array(true), $this->object->isMimeType($fileArray, 'image/jpeg'));
    }
}
