<?php

namespace MetaSyntactical\Mime\Tests;

use MetaSyntactical\Mime\Magic;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-22 at 19:55:46.
 */
class MagicTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Magic
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Magic;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        Magic::setDefaultMagicFile();
    }

    public function testExpectedExceptionIsThrownIfProvidedMagicFileDoesNotExist()
    {
        $this->setExpectedException(
            'MetaSyntactical\\Mime\\Exception\\FileNotFoundException',
            'File does not exist or is not readable:'
        );
        new Magic('/notExistingDummyPath/magic');
    }

    /**
     * @covers MetaSyntactical\Mime\Magic::setDefaultMagicFile
     */
    public function testSettingNonExistingDefaultMagicFileThrowsException()
    {
        $this->setExpectedException(
            'MetaSyntactical\\Mime\\Exception\\FileNotFoundException',
            '/notExistingDummyPath/magic'
        );
        Magic::setDefaultMagicFile('/notExistingDummyPath/magic');
    }

    /**
     * @covers MetaSyntactical\Mime\Magic::setDefaultMagicFile
     */
    public function testDefaultMagicFileIsUsedOnInitialization()
    {
        Magic::setDefaultMagicFile(__DIR__.'/_Data/magic');
        $magic = new Magic();
        self::assertNull($magic->getMimeType(__DIR__.'/_Data/magic'));
    }
}
