<?php

namespace MetaSyntactical\Mime;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-22 at 19:55:46.
 */
class MagicTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Magic
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Magic;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testThatExpectedExceptionIsThrownIfProvidedMagicFileDoesNotExist()
    {
        $this->setExpectedException(
            'MetaSyntactical\\Mime\\Exception\\FileNotFoundException',
            'File does not exist or is not readable:'
        );
        new Magic('/notExistingDummyPath/magic');
    }
}
